### ISSUE TITLE
Cannot connect through Foxglove bridge

### ISSUE THREAD

**Issue by mvanlobensels** [Lichtblick-Suite/lichtblick#153]
Dear Lichtblick team,

Lichtblick worked perfectly for me when connecting to my ROS2 system through the Foxglove bridge. Recently, this stopped working out of the blue. I have the feeling this happened when I updated my system, which upgraded `ros-humble-foxglove-bridge` to version 0.8.0. Have you experienced this issue?

I just get a black screen for the 3D and image panels, even though the camera and lidar topics are recongnized in the Topic panel

![image](https://github.com/user-attachments/assets/64ec7cd9-f4eb-49ab-b119-ae3307559b97)

- Version: 1.3.6
- Platform: Pop_OS 22.04
- Data source: ROS2 native through Foxglove bridge

**Comment by luluiz** [comment]
Hi @mvanlobensels, 
I've opened an image and 3D panel using a WS connection and it works properly.
Could you check once again and provide more information about this behaviour?
If it persists, I'd say to run in dev mode to monitor the logs via the "Console" tab and provide us with more information.

**Comment by luluiz** [comment]
I will close the issue due to lack of response from the user, but if it occurs again, please feel free to reopen the issue.
