### ISSUE TITLE
Reminder: Electron version "end of life suppport"

### ISSUE THREAD

**Issue by jdsika** [Lichtblick-Suite/lichtblick#225]
Maybe I am running into an issue because of the use of an old version:
https://github.com/electron/electron/issues/44295

Update: pretty sure my error has noting to do with the version. Maybe just consider this as a reminder that the electron version is not supported anymore

**Comment by laisspportugal** [comment]
Hello @jdsika, thanks for the reminder.
We will treat it internally in order to perform the update of electron. 
Since Lichtblick is working properly and it does not affect the user experience, we will close this issue.
