### ISSUE TITLE
Text missing on MacOS Menubar

### ISSUE THREAD

**Issue by KisonHe** [Lichtblick-Suite/lichtblick#227]
**Description**

Some text missing on MacOS menu bar.

- Version: 1.5.0
- Platform: MacOS Sequoia 15.0.1, M3 Chip
- Data source (e.g. bag file, mcap file, rosbridge, ROS 1/2 native): Not related

**Steps To Reproduce**

1. Open the app, and click menubar. 

[
<img width="262" alt="截屏2024-10-18 18 21 19" src="https://github.com/user-attachments/assets/8fed1b00-bb59-452a-9195-db694d599a77">
](url)

**Expected Behavior**

Texts should be there

**Comment by laisspportugal** [comment]
Hi @KisonHe, thank you for your feedback.
We are investigating this issue on our side.

**Comment by Woodii1998** [comment]
> Hi @KisonHe, thank you for your feedback. We are investigating this issue on our side.

Do you need help, I can help fix this problem

**Comment by aneuwald-ctw** [comment]
@KisonHe we are closing this issue, as it was resolved in the PR #237 and is also available in the new release of version 1.7.0.
https://github.com/Lichtblick-Suite/lichtblick/releases/tag/v1.7.0

Thanks for your contribution and hope you keep enjoying and contribution to Lichtblick!
